// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("61b18c0a-c4f7-432f-9801-a69da41bb34d"),
	startsWith("7ef35dc9-94ba-461e-87b0-f27b3509cdc2"),
	endsWith("7eba1727-1572-4435-a628-7f478fa2f6e9"),
	between("41bc3256-ad23-47e3-b74c-935c59c86289"),
	greater("1eac943d-073c-49ec-8e22-30803bf20afa"),
	greaterEqual("959e4406-115e-4b83-9b43-4cab04ad13eb"),
	equal("01a50b67-d215-4157-ade9-77741f39b533"),
	notEqual("ed2881d1-5c83-4402-a4ea-33f809312c15"),
	smaller("b03c899e-f0b8-4053-bdcb-c7b086fe78e5"),
	smallerEqual("060c5914-d482-4f92-8190-c508d14e51c2"),
	empty("e5586409-577a-4b67-90eb-36fa2738a8df"),
	notEmpty("591541c1-df94-4e54-bdbe-2d230fb0bc83");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
