// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("8e92658f-04bd-44d8-b039-abee9a1f6dbd"),
	startsWith("33b05276-a746-4920-bb98-7ce16f81ea86"),
	endsWith("3f228bf4-5b23-4be4-8e21-1fb7f549be82"),
	between("4ec5c281-8412-426e-b60c-7006d7196f5d"),
	greater("37ef6694-af56-4331-8bf1-49134076b8c1"),
	greaterEqual("acc297f1-7f20-4ba8-9c8b-21db4e289918"),
	equal("e19235f1-7acc-40b2-b474-627c45140568"),
	notEqual("19021efd-3916-4df8-9e09-3df5498e97ae"),
	smaller("0fc4af58-5dcc-4bad-8d36-111befbc340c"),
	smallerEqual("f4ae52e4-220a-4db1-a31c-498dfc5565ff"),
	empty("1dba0834-8717-415b-bed5-4b83b3a11641"),
	notEmpty("1383632e-44b0-4f25-9cce-824cb1c2af58");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
