// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("8d89b402-fea6-4a52-86c6-681d0d07fbcc"),
	denied("0e001168-24e0-4342-9e27-a58cdcbed2af"),
	limited("2e7a376e-8493-40f2-8814-7ec344baf054"),
	granted("34314aed-7a4a-4668-a0d1-f1b765841c9b"),
	blocked("eebf6a36-b43d-44d7-921a-505d51610330");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
