// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("e5347a72-d7dc-4842-9ed5-4ab80286f516"),
	denied("0fdb2f77-bae6-41c4-9ae6-615002f3f432"),
	limited("7f4d7b3a-b892-427c-a63a-b8dde1b37ddf"),
	granted("8da2742b-f4ba-4b39-926a-48c5c1d0b887"),
	blocked("ad0561a7-1f35-47a9-ab8a-a0d9411a18cc");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
