// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("a7d5e0fe-57ed-46ec-b385-e8477753d14d"),
	low("2b27b38f-e378-45bd-89fe-734bd4f41916"),
	medium("474c3187-c6a9-4a73-8ea1-f3ebba942e8a"),
	high("22bc526b-3992-4183-8d6f-08344f38b4b6"),
	custom("8a878dfd-7eec-4e4a-88ad-7a6a2c20b05a");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
