// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("811bfa04-624d-474d-9923-6ec23b29df38"),
	low("1c8652e0-a001-4997-8c93-6381d1e68086"),
	medium("9970b57f-5fb1-41c3-b880-536faa267906"),
	high("f6fc0850-f401-433a-92a7-e949a717ff6d"),
	custom("8b462a5b-6689-4a1d-a872-510ada336d45");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
