// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum StatusBarHideShowAnimation
{
	none("63c92e4a-a02b-4f67-98b3-8512c0fdb785"),
	fade("0d10464b-ef2d-49d9-900e-6729759cec5f"),
	slide("b39e444f-42e0-4f3a-bed7-cf9a4ff7f1bf");

	private final java.lang.String i18nCaptionKey;
	
	private StatusBarHideShowAnimation(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
